EXIT_MESSAGE:str = 'Goodbye!'
ENTERED_NUMBER:str = 'Number entered is: {0}'
GET_NUMBER_WARNING:str = 'Invalid input entered.' + '\n' + 'Please enter an integer value.'
GET_PRIME_START_WARNING:str = 'Invalid input: Enter an integer >= 2.'
PRIME_NUMBER_INVALID:str = 'Invalid input: Expected a positive number.'