"""
    Guess a number between a range of random numbers.

    @datetime:: June 15, 2026 8:19 am (UTC-5)
    @author:: jac0der
"""
import random as r
import guess_constants as gc
import guess_result_enum
from py_custom import jaclog, jacexit as je

logger = jaclog.configure('guess_number', './guess_number.log')


def get_number()->int:
    """
    Used to get the number from user to check 
    if in random range.

    Args: 
        None

    Returns:
        int: Number to check if in random range.
    """
    logger.info("Getting number from user to check if it is in random range.")

    while True:

        try:
            value = input("Enter number (q to quit): ")

            if value.strip().lower() == 'q':
                je.exit_program(gc.EXIT_MESSAGE, logger)

            number = int(value)
            print(gc.USER_NUMBER_MSG.format(number))
            logger.info(gc.USER_NUMBER_MSG.format(number))

            return number

        except ValueError:
            print(gc.GET_NUMBER_WARNING)
            logger.warning(gc.GET_NUMBER_WARNING)
        

def generate_random_number()->int:
    """
    Generate the random number the user number is checked against.

    Args:
        None

    Returns:
        int: The number generated within a range
             to compare with user input number.
    """
    logger.info("Generating random number from range.")

    random_number = r.randint(gc.START_INT, gc.END_INT)
    print(gc.RANDOM_NUMBER_MSG.format(random_number))
    logger.info(gc.RANDOM_NUMBER_MSG.format(random_number))

    return random_number


def compare_numbers(user_guess_number:int, random_number:int)->int:
    """
    Compare the user guessed number with the randomly generated
    number to see if they match.

    Args:
        user_guess_number (int): The number guessed by the user.
        random_number (int): The number randomly generated by the program.

    Returns:
        int: 
            -1 if guess is low
            0 if correct
            1 if guess is high
    """
    logger.info("Comparing the guessed user number with the random generated number.")

    if not isinstance(user_guess_number, int):
        raise TypeError(f"user_guess_number must be int, got {type(user_guess_number).__name__}")

    if not isinstance(random_number, int):
        raise TypeError(f"random_number must be int, got {type(random_number).__name__}")

    if user_guess_number < random_number:
        return GuessResult.LOW

    if user_guess_number > random_number:
        return GuessResult.HIGH

    return GuessResult.CORRECT


def main()->None:
    """ Main function to start Guess Number Program. """

    try:
        logger.info("Starting the Guess Number  Program...")
        guessing = True

        while guessing:

            tries_counter = gc.TRIES
            random_number = generate_random_number()

            for n in range(gc.TRIES):

                user_number = get_number()        
                result = compare_numbers(user_number, random_number)

                if result == GuessResult.CORRECT:
                    print("You have gussed the correct number.")
                    startover = input("Do you want to start over (Y or N)?")
                    if startover.strip().lower() == 'y':
                        break
                    else:
                        guessing = False
                        break

                elif result == GuessResult.LOW:
                    tries_counter -= 1
                    print(f"Too low. You have {tries_counter} tries remaining. Try again. \n")

                elif result == GuessResult.HIGH:
                    tries_counter -= 1
                    print(f"Too high. You have {tries_counter} tries remaining. Try again. \n")

                if tries_counter == 0:
                    print("You have no more tries remaining.")
                
                    startover = input("Do you want to start over (Y or N)?")
                    if startover.strip().lower() == 'y':
                        break
                    else:
                        guessing = False
                        break           

    except TypeError as ex:
        logger.error(f"TypeError: {ex}")

    except KeyboardInterrupt as ex:
        je.exit_program(f"\n{gc.EXIT_MESSAGE}", logger)

    except EOFError as ex:
        je.exit_program(f"\n{gc.EXIT_MESSAGE}", logger)

    except Exception as ex:
        logger.exception("Error occurred in main Guess Number function.")


if __name__ == "__main__":
    main()